# Generated by Django 3.2.9 on 2022-02-26 13:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название альбома')),
                ('slug', models.SlugField()),
                ('song_list', models.TextField(blank=True, null=True, verbose_name='Трек-лист')),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата релиза')),
                ('description', models.TextField(verbose_name='Описание альбома')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_alb/')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Исполнитель/группа')),
                ('slug', models.SlugField()),
                ('desc', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_prof/')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название жанра')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание жанра')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название медианосителя')),
            ],
            options={
                'verbose_name': 'Медианоситель',
                'verbose_name_plural': 'Медианосители',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя музыканта')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_member/')),
            ],
            options={
                'verbose_name': 'Музыкант',
                'verbose_name_plural': 'Музыканты',
            },
        ),
        migrations.CreateModel(
            name='SingleMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название трека')),
                ('title', models.CharField(max_length=255, verbose_name='Тип альбома')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('created_music', models.DateTimeField(auto_now_add=True)),
                ('image_track', models.ImageField(upload_to='image_track/', verbose_name='Обложка трека')),
                ('music_upload', models.FileField(upload_to='music_load/')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.album', verbose_name='Альбом')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.artist', verbose_name='Исполнитель')),
                ('gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Загрузка трека',
                'verbose_name_plural': 'Загрузка трека',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(max_length=200, verbose_name='Имя комментатора')),
                ('comment_body', models.TextField(verbose_name='Текст комментария')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Время создания комментария')),
                ('profile_image', models.ImageField(null=True, upload_to='comment_image_prof/', verbose_name='Картинка профиля')),
                ('parrent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='application.singlemusic', verbose_name='Трэк')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.genre', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='artist',
            name='members',
            field=models.ManyToManyField(related_name='artist', to='application.Member', verbose_name='Участник'),
        ),
        migrations.CreateModel(
            name='AnswerComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(max_length=200, verbose_name='Имя комментатора')),
                ('comment_body', models.TextField(verbose_name='Текст комментария')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Время создания комментария')),
                ('profile_image', models.ImageField(upload_to='comment_image_prof/', verbose_name='Картинка профиля')),
                ('parrent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='application.comment', verbose_name='Ответ на коммент')),
            ],
            options={
                'verbose_name': 'Ответ на комментарий',
                'verbose_name_plural': 'Ответ на комментарий',
            },
        ),
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.artist', verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='album',
            name='gen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.genre', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='album',
            name='mediatype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.mediatype', verbose_name='НОСИТЕЛЬ(CD-DVD, PLAYER, Флешка)'),
        ),
    ]
