# Generated by Django 3.2.9 on 2022-04-20 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название альбома')),
                ('slug', models.SlugField()),
                ('song_list', models.TextField(blank=True, null=True, verbose_name='Трек-лист')),
                ('release_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата релиза')),
                ('description', models.TextField(verbose_name='Описание альбома')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_alb/')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Исполнитель/группа')),
                ('slug', models.SlugField()),
                ('desc', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_prof/')),
            ],
            options={
                'verbose_name': 'Исполнитель',
                'verbose_name_plural': 'Исполнители',
            },
        ),
        migrations.CreateModel(
            name='ChangeContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=250, verbose_name='Главный заголовок')),
                ('title', models.CharField(max_length=250, verbose_name='над главным заголовок')),
                ('contact_title', models.CharField(max_length=250, verbose_name='Заголовок блока контактов')),
                ('map_adress', models.CharField(max_length=250, verbose_name='Адресс, где находится офис')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Контактный E-mail')),
                ('vk_url', models.CharField(max_length=250, verbose_name='Ссылка на вк')),
                ('facebook_url', models.CharField(max_length=250, verbose_name='Ссылка на фейсбук')),
                ('twitter_url', models.CharField(max_length=250, verbose_name='Ссылка на твиттер')),
                ('inst_url', models.CharField(max_length=250, verbose_name='Ссылка на инстаграмм')),
                ('tik_tok_url', models.CharField(max_length=250, verbose_name='Ссылка на тик ток')),
            ],
            options={
                'verbose_name': 'Замена контактной информации',
                'verbose_name_plural': 'Замена контактной информации',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название жанра')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Описание жанра')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название медианосителя')),
            ],
            options={
                'verbose_name': 'Медианоситель',
                'verbose_name_plural': 'Медианосители',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя музыканта')),
                ('slug', models.SlugField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_member/')),
            ],
            options={
                'verbose_name': 'Музыкант',
                'verbose_name_plural': 'Музыканты',
            },
        ),
        migrations.CreateModel(
            name='PostReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя отправителя отзыва')),
                ('email', models.EmailField(max_length=254, verbose_name='Емаил для связи')),
                ('subject', models.CharField(max_length=250, verbose_name='Тема сообщения')),
                ('text', models.TextField(verbose_name='Текст обращения')),
            ],
            options={
                'verbose_name': 'Отзыв на сайте',
                'verbose_name_plural': 'Отзыв на сайте',
            },
        ),
        migrations.CreateModel(
            name='SingleMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название трека')),
                ('title', models.CharField(max_length=255, verbose_name='Тип альбома')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('created_music', models.DateTimeField(auto_now_add=True)),
                ('image_track', models.ImageField(upload_to='image_track/', verbose_name='Обложка трека')),
                ('music_upload', models.FileField(upload_to='music_load/')),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.album', verbose_name='Альбом')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.artist', verbose_name='Исполнитель')),
                ('gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Загрузка трека',
                'verbose_name_plural': 'Загрузка трека',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254)),
                ('desc', models.TextField()),
                ('date_of_birth', models.DateTimeField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_profile/')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='poh_art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.artist', verbose_name='Артисты')),
                ('gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.genre', verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_name', models.CharField(max_length=200, verbose_name='Имя комментатора')),
                ('comment_body', models.TextField(verbose_name='Текст комментария')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Время создания комментария')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='comment_image_prof/', verbose_name='Картинка профиля')),
                ('parrent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='application.singlemusic', verbose_name='Трэк')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='application.comment')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.genre', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='artist',
            name='members',
            field=models.ManyToManyField(related_name='artist', to='application.Member', verbose_name='Участник'),
        ),
        migrations.AddField(
            model_name='album',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.artist', verbose_name='Исполнитель'),
        ),
        migrations.AddField(
            model_name='album',
            name='gen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.genre', verbose_name='Жанр'),
        ),
        migrations.AddField(
            model_name='album',
            name='mediatype',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.mediatype', verbose_name='НОСИТЕЛЬ(CD-DVD, PLAYER, Флешка)'),
        ),
    ]
