# Generated by Django 3.2.9 on 2022-02-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата релиза'),
        ),
    ]
