# Generated by Django 3.2.9 on 2022-02-28 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_alter_album_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='self_alb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.album', verbose_name='Альбом'),
        ),
    ]
