# Generated by Django 3.2.9 on 2022-04-22 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_remove_comment_comment_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='profile_image',
        ),
    ]
