# Generated by Django 3.2.9 on 2022-02-28 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_album_self_alb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='self_alb',
        ),
    ]
