# Generated by Django 3.2.9 on 2022-03-02 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_album_self_alb'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя отправителя отзыва')),
                ('email', models.EmailField(max_length=254, verbose_name='Емаил для связи')),
                ('subject', models.CharField(max_length=250, verbose_name='Тема сообщения')),
                ('text', models.TextField(verbose_name='Текст обращения')),
            ],
        ),
    ]
