# Generated by Django 3.2.9 on 2022-03-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0006_postreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postreview',
            options={'verbose_name': 'Отзыв на сайте', 'verbose_name_plural': 'Отзыв на сайте'},
        ),
        migrations.AlterField(
            model_name='postreview',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Емаил для связи'),
        ),
    ]
