# Generated by Django 3.2.9 on 2022-03-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20220302_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreview',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Емаил для связи'),
        ),
    ]
