# Generated by Django 3.2.9 on 2022-05-02 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_profile_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
