# Generated by Django 3.2.9 on 2022-03-03 14:09

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_alter_postreview_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=250, verbose_name='Главный заголовок')),
                ('title', models.CharField(max_length=250, verbose_name='над главным заголовок')),
                ('contact_title', models.CharField(max_length=250, verbose_name='Заголовок блока контактов')),
                ('map_adress', models.CharField(max_length=250, verbose_name='Адресс, где находится офис')),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('email', models.EmailField(max_length=254, verbose_name='Контактный E-mail')),
                ('vk_url', models.CharField(max_length=250, verbose_name='Ссылка на вк')),
                ('facebook_url', models.CharField(max_length=250, verbose_name='Ссылка на фейсбук')),
                ('twitter_url', models.CharField(max_length=250, verbose_name='Ссылка на твиттер')),
                ('inst_url', models.CharField(max_length=250, verbose_name='Ссылка на инстаграмм')),
                ('tik_tok_url', models.CharField(max_length=250, verbose_name='Ссылка на тик ток')),
            ],
            options={
                'verbose_name': 'Замена контактной информации',
                'verbose_name_plural': 'Замена контактной информации',
            },
        ),
        migrations.CreateModel(
            name='poh_art',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.artist', verbose_name='Артисты')),
                ('gen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.genre', verbose_name='Жанр')),
            ],
        ),
    ]
