# Generated by Django 3.2.9 on 2022-03-15 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_auto_20220310_1505'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnswerComment',
        ),
    ]
