# Generated by Django 3.2.9 on 2022-05-02 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_imageprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.AlterField(
            model_name='imageprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_profile/'),
        ),
    ]
