# Generated by Django 3.2.9 on 2022-03-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0012_delete_answercomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_image_prof/', verbose_name='Картинка профиля'),
        ),
    ]
