# Generated by Django 3.2.9 on 2022-05-02 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0014_alter_imageprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='profile',
            name='ava',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.imageprofile', verbose_name='Аватарка'),
        ),
    ]
