# Generated by Django 3.2.9 on 2022-05-02 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0015_auto_20220502_2230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='ava',
        ),
        migrations.AddField(
            model_name='imageprofile',
            name='key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='application.profile', verbose_name='Аватарка'),
        ),
        migrations.AlterField(
            model_name='imageprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_prof/group/'),
        ),
    ]
