# Generated by Django 3.2.9 on 2022-04-20 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_blog', models.CharField(max_length=255, verbose_name='Тип Поста')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок поста')),
                ('slug', models.SlugField(unique_for_date='publish')),
                ('pre_body', models.TextField(verbose_name='Описание поста на предисловие')),
                ('body', models.TextField(verbose_name='Описание поста полным текстом')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('image_blog', models.ImageField(upload_to='image_blog/', verbose_name='Картинка блога')),
                ('status', models.CharField(choices=[('close', 'Close'), ('published', 'Published')], default='published', max_length=15, verbose_name='Статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Владелец поста')),
            ],
            options={
                'ordering': ('-publish',),
            },
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_name', models.CharField(max_length=255, verbose_name='Название категории')),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='CommentBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя комментатора')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255, verbose_name='Тема комментария')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('comment_created', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.commentblog')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.blog')),
            ],
            options={
                'verbose_name': 'Комментарий к блогу',
                'verbose_name_plural': 'Комментарий к блогу',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.categorylist', verbose_name='Выбор категории'),
        ),
    ]
