# Generated by Django 3.2.9 on 2022-03-10 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20220305_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentblog',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.commentblog'),
        ),
    ]
